### ISSUE TITLE
Filter list in WMS add layer dialog

### ISSUE THREAD

**Issue by 3nids** [opengisch/QGIS_tiny_features#22]
It's often difficult to retrieve a layer in these dialogs.
Add a line edit to filter the layers by their names

**Comment by rbovard** [comment]
Is it not already the case?

At least for PG:

![image](https://user-images.githubusercontent.com/4549666/75772254-e1c5fa00-5d4b-11ea-9c3b-36538880bf5c.png)

**Comment by 3nids** [comment]
apparently, so only WMS then!

**Comment by 3nids** [comment]
implemented in https://github.com/qgis/QGIS/pull/36166
