### ISSUE TITLE
Improve preview of results in expression editor

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QGIS_tiny_features#26]
In the expression editor, the expression result preview is always using the first record.

It would be useful, if the expression context returns multiple features that one can step through each feature, starting from the first feature to the next, maybe with shortcuts to first and last feature.

That way it would be easier to evaluation if the expression works as expected.

**Comment by andreasneumann** [comment]
![image](https://user-images.githubusercontent.com/884476/75772140-a5929980-5d4b-11ea-95fd-b467ad1d9b22.png)

**Comment by 3nids** [comment]
side works:
* https://github.com/qgis/QGIS/pull/35378
* https://github.com/qgis/QGIS/pull/35386

**Comment by 3nids** [comment]
and here it goes....
https://github.com/qgis/QGIS/pull/36089
it was much more work than expected!

**Comment by andreasneumann** [comment]
Thanks for implementing it!
